### ISSUE TITLE
if someone buys my nft I doesn't reiceive the funds in my wallet 

### ISSUE THREAD

**Issue by souravnmaji** [chrisstef/polyplace#2]
when i have listed my nft for sale and when someone buys my NFT i DOESN'T receive the funds in my wallet

**Comment by chrisstef** [comment]
> when i have listed my nft for sale and when someone buys my NFT i DOESN'T receive the funds in my wallet

There is a bug on the smart contract, where sometimes the funds are being send to the burn address. This bug occurs under unknown circumctances. I proceed with solving the error but will need a contract redeploy. Stay tuned!

**Comment by souravnmaji** [comment]
Hi , I saw the new repo but there is one more issue I guess because I am unable to see any withdraw function to take out the Nft listing fees from the smart contract

**Comment by ghost** [comment]
was this bug happening because when an item is listed, the .seller in the struct isnt set to the msg.sender? so in the createMarketSale function, where you assign creator to be the .seller, this is where the issue occurs?

**Comment by chrisstef** [comment]
I believe the issue was because the seller is set to the marketplace (which is correct) but later the seller (now the marketplace) receives the asking price. The missleading "seller" was causing funds to transfer in zero address.
I fixed it by storing the creator address in a creator variable before the seller gets changed to the marketplace and then instead of sending the asking price to the seller of the token I send it to the creator.

**Comment by ditholease** [comment]
Can you withdraw the market fee somehow?
